[package]
name = "rustwordle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
libm = "0.2.2"
text_io = "0.1.10"
itertools = "0.10.3"
